### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#1]
**EPIC:** [User Access](#6 )

As a **New User** I can **create an account** so that **I can login in future**

**Acceptance Criteria:**
- [x] - Register a New Account
- [x] - Registration form validates details
- [x] - User receives confirmation of account creation

**Tasks:**
- [x] - Create sign up form/link
- [x] - Set up User account database
- [x] - Validate and confirm creation of new user
- [x] - Code a feedback response for the user
