### ISSUE TITLE
USER STORY: Landing Page

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#10]
**EPIC:** <epic>

As a **Visiting Customer** I can **view the welcome landing page** so that **I quickly know what the purpose of the site is**

**Acceptance Criteria:**
- [x] Easy to understand and use navigation
- [x] Responsive design
- [x] Clear easy to understand welcome page describing the purpose of the site

**Tasks:**
- [x] Design welcome landing page
