### ISSUE TITLE
USER STORY: Templates and Bootstrap

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#12]
**EPIC:** [Templates Navigation and Styles](#11 )

**User Story:** As a **Developer**, I can **set up a base template with Bootstrap CSS and JavaScript files**, so that the site has a **consistent look and feel**.

**Acceptance Criteria:**

- [x] The base template includes the necessary Bootstrap CSS and JavaScript files.

**Tasks:**

- [x] Research and install the necessary Django packages for Bootstrap integration.
- [x] Create a base template file (`base.html`) and include the necessary Bootstrap CSS and JavaScript files.
