### ISSUE TITLE
USER STORY: Create footer

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#15]
**EPIC:** [Templates Navigation and Styles](#11 )

**User Story:** As a **Developer**, I can **design and implement a footer using Bootstrap components**, so that **users can easily find important information about the site.**

**Acceptance Criteria:**

- [x] The base template includes a footer with appropriate styling.

**Tasks:**

- [x] Design and implement a footer using Bootstrap components.
- [x] Link footer if necessary to base.html
