### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#2]
**EPIC:** [User Access](#6 )

As a **Existing User** I can **login using my credentials** so that **I can access user specific content**

**Acceptance Criteria:**

- [x] User can login with correct details
- [x] Incorrect details give error message
- [x] When logged in it is clearly indicated what user is logged in

**Tasks:**
- [x] Create login function
- [x] Ensure login is successful and display confirmation
- [x] Display error message when failed login
- [x] Display current user
