### ISSUE TITLE
USER STORY: Set up a testing framework

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#27]
**EPIC:** [Implementing Tests](#26)

As a **Developer** I can **set up a testing framework** so that **I can write and run tests for my code**

**Acceptance Criteria:**
- [x] A testing framework is installed and configured
- [x] The framework is integrated with the project

**Tasks:**
- [x] Research and choose a testing framework
- [x] Install the testing framework
- [x] Configure the framework for the project
