### ISSUE TITLE
USER STORY: Write unit tests for existing code

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#28]
**EPIC:** [Implementing Tests](#26)

As a **Developer** I can **write unit tests for existing code** so that **I can ensure individual components work as expected**

**Acceptance Criteria:**
- [x] Unit tests are written for all existing functions and methods
- [x] All unit tests pass successfully

**Tasks:**
- [x] Identify key functions and methods to test
- [x] Write unit tests for identified functions and methods
- [x] Run unit tests and ensure they pass
