### ISSUE TITLE
USER STORY: Write integration tests

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#29]
**EPIC:** [Implementing Tests](#26)

As a **Developer** I can **write integration tests** so that **I can ensure different parts of the system work together correctly**

**Acceptance Criteria:**
- [ ] Integration tests are written for key interactions between components
- [ ] All integration tests pass successfully

**Tasks:**
- [ ] Identify key interactions to test
- [ ] Write integration tests for identified interactions
- [ ] Run integration tests and ensure they pass
