### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#3]
**EPIC:** [User Access](#6 )

As a **logged in user** I can **logout** so that **I can keep my account secure**

**Acceptance Criteria:**
- [x] User can see log out link when logged in
- [x] Log out link logs user out of the site
- [x] Confirmation is given that user has been logged out successfully

**Tasks:**
- [x] Create logout functionality
- [x] Give confirmation that logout has been successful
