### ISSUE TITLE
USER STORY: Write end-to-end tests

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#30]
**EPIC:** [Implementing Tests](#26)

As a **Developer** I can **write end-to-end tests** so that **I can ensure the entire application works as expected from the user's perspective**

**Acceptance Criteria:**
- [ ] End-to-end tests are written for key user flows
- [ ] All end-to-end tests pass successfully

**Tasks:**
- [ ] Identify key user flows to test
- [ ] Write end-to-end tests for identified user flows
- [ ] Run end-to-end tests and ensure they pass
