### ISSUE TITLE
USER STORY: Set up continuous integration for tests

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#31]
**EPIC:** [Implementing Tests](#26)

As a **Developer** I can **set up continuous integration for tests** so that **tests are run automatically on code changes**

**Acceptance Criteria:**
- [ ] Continuous integration is set up to run tests on code changes
- [ ] Notifications are sent for test results

**Tasks:**
- [ ] Choose a continuous integration service
- [ ] Configure the service to run tests on code changes
- [ ] Set up notifications for test results
