### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#4]
**EPIC:** [User Access](#6 )

As a **logged in user** I can **delete my account** so that **I can remove my account from the site**

**Acceptance Criteria:**
- [x] User can remove account from site
- [x] Warning and confirmation required
- [x] Upon removal all user data is also removed

**Tasks:**
- [x] Create delete user functionality
- [x] Create a required second step with warning and confirmation before account is removed
- [x] Remove all related entries from database
- [x] Give confirmation that account has been removed
