### ISSUE TITLE
TEST: Booking App Model Tests

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#40]
**EPIC:** [Implementing Tests](#26 )

As a **developer** I can **run tests on the Event, Availability, and Booking models** so that **I can ensure the models behave as expected**

**Acceptance Criteria:**
- [ ] The event should have the correct available slots
- [ ] The event location should match the expected value
- [ ] The event start time should be before the stop time
- [ ] The booking user should match the created user
- [ ] The booking slot should match the created availability
- [ ] The number of guests should be correctly set
- [ ] The booking should be confirmed
- [ ] The user comments should match the expected value
- [ ] The staff comments should match the expected value
- [ ] The availability should be linked to the correct event
- [ ] The availability booked status should be correctly set

**Tasks:**
- [ ] Create a user and an event for testing
- [ ] Create an availability slot linked to the event
- [ ] Create a booking linked to the user and availability slot
- [ ] Assert that the event has the correct available slots
- [ ] Assert that the event location matches the expected value
- [ ] Assert that the event start time is before the stop time
- [ ] Assert that the booking user matches the created user
- [ ] Assert that the booking slot matches the created availability
- [ ] Assert that the number of guests is correctly set
- [ ] Assert that the booking is confirmed
- [ ] Assert that the user comments match the expected value
- [ ] Assert that the staff comments match the expected value
- [ ] Assert that the availability is linked to the correct event
- [ ] Assert that the availability booked status is correctly set
