### ISSUE TITLE
USER STORY: Install and set up Django

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#7]
**EPIC:** [Initial Django Setup](#5 )

As a **Developer** I want to **Install and set up Django and all related libraries** so that **I can begin development of the site**

**Acceptance Criteria:**
- [ ] Django Installed
- [ ] Related libraries installed

**Tasks:**
- [x] Install Django
- [x] Install and connect the database
- [x] Install and connect Cloudinary
- [x] Create and populate a requirements.txt file
- [x] Create a Django project
- [x] Create the first app needed and connect it in settings.py
