### ISSUE TITLE
USER STORY: Secure Config Variables

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#8]
**EPIC:** [Initial Django Setup](#7 )

As a **Developer** I want to **set up the environment to secure secret configuration variables** so that **Sensive data is ept private**

**Acceptance Criteria:**
- [x] env.py file created with secure variables
- [x] .gitignore file updated to include .env file
- [x] settings file updated to point to location for secure variables

**Tasks:**
- [x] Create env.py file and store the secret environment variables
- [x] Make sue env.py file is added to .gitignore to prevent pushing sensitive data to GitHub
- [x] Adjust settings and code to point to the location of any secret variables
