### ISSUE TITLE
USER STORY: Deployment to Heroku

### ISSUE THREAD

**Issue by Hedgemonkey** [Hedgemonkey/munchmonkey#9]
**EPIC:** [Initial Django Setup](#7 ) 

As a **Developer** I want to **deploy the site to Heroku** so that **I can ensure the site works on Heroku and I can share the completed site publicly**

**Acceptance Criteria:**
- [ ] Site is deployed to Heroku and loads

**Tasks:**
- [ ] Create a new Heroku app
- [ ] Add config vars in Heroku settings
- [ ] Create Procfile and add to project
- [ ] Add Heroku as an allowed host in Django settings
- [ ] Connect the new Heroku app to GitHub repository
- [ ] Deploy site
